Code Optimization and Refactoring
udohPixel/stackoverflow_lite pull request #38
Opened 2023-01-16 05:42 UTC by udohPixel

2023-01-19 20:18 UTC, kufre-okon requested changes
Good work

2023-01-25 01:31 UTC, udohPixel commented on answers/helpers/answerFilters.js
> +      });
Yes, it is. It was set as a unique field.

2023-01-25 02:28 UTC, udohPixel commented on answers/helpers/answerFilters.js
> +  filterItems: async (QuestionId, queryStr) => {
I changed it so I could easily recognise the request that was coming from `req.body` {I used QuestionId in this case} and `req.params` {I used questionId in this case}, without having to go to the controller each time to check.
Same goes for all others AnswerId, CommentId etc.

2023-01-25 02:29 UTC, udohPixel commented on answers/helpers/answerFilters.js
> +      });
Okay boss. I will follow through in subsequent projects. Thanks. 👍

2023-01-25 02:32 UTC, merged